### ISSUE TITLE
P-ODM Not working with the latest node + mongo

### ISSUE THREAD

**Issue by syilmaz** [pmlopes/p-odm#11]
Does this run in the cloud?

Kind regards,
Mike Hoogervorst and Samet Yilmaz

**Comment by pmlopes** [comment]
I've no idea :P
I haven't update this in years!

**Comment by syilmaz** [comment]
I've tried to run this, but it says I need something called "Java script" is that related to coffee?

**Comment by pmlopes** [comment]
You know there this cool thing called [vert.x](http://vertx.io) that some say is [faster](https://www.techempower.com/benchmarks/previews/round13/#section=data-r13&hw=sc&test=json) than that "Java script" thing of yours :P
